- name: Copy docker compose 
  copy:
        src: /root/docker-compose-full.yaml
        dest: /home/ashiwaju/docker-compose.yaml
            
- name: Docker login
  docker_login:
          username: ashiwaju
          password: "{{docker_password}}"

- name: Start containers from compose
  community.docker.docker_compose_v2:
        project_src: /home/ashiwaju